name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: gcc9
      run: sudo add-apt-repository ppa:ubuntu-toolchain-r/test && sudo apt update && sudo apt install gcc-9 g++-9
    - name: Install dependencies
      run: sudo apt update && sudo apt install build-essential qt5-default cmake qtwebengine5-dev libboost-all
    - name: cmake
      run: CC="gcc-9" CXX="g++-9" cmake .
    - name: make
      run: make
